🎉 Listen Page V1 (Standby API)
AnthonyBourret/Soundy pull request #18
Opened 2024-02-05 20:36 UTC by AnthonyBourret

2024-02-27 22:05 UTC, Joliwood requested changes

2024-02-27 22:05 UTC, Joliwood commented on src/components/listenPage/SongDisplay.tsx
> +import SongCard from '../customElements/SongCard';
en profiter pout passer tous les custom elements en barrel exports stp

2024-02-27 22:05 UTC, Joliwood commented on src/svg/addIconChecked.tsx
> +function AddIconChecked({ width, height }: Props): React.JSX.Element {
React en premier inuital car déjà importé ligne 1

2024-02-27 22:05 UTC, Joliwood commented on src/svg/addIconChecked.tsx
> +interface Props {
exporter si elle n'existe pas déjà en prop générique pour tous les svg (avec couleur en option, ce serait cool)

2024-02-27 22:05 UTC, Joliwood commented on src/svg/addIconUnchecked.tsx
> +interface Props {
idem prop exportée

2024-02-27 22:05 UTC, Joliwood commented on src/tests/CapitalizeFirstLetter.test.ts
> +});
Pas logique justement, quitte à avoir une fonction qui formatte, autant formater le reste des lettres en minuscule

2024-02-27 22:05 UTC, Joliwood commented on src/tests/SecondsToMinutes.test.ts
> +import secondsToFormatedDuration from '../utils/SecondsToFormatedDuration';
importer depuis utils seulement

2024-02-28 13:35 UTC, AnthonyBourret commented on public/locales/en/common.json
> +    "ORDER_SELECT_NAME_ZA": "Name, Z-A",
Je ne vois pas l'intérêt de mettre 2 lettres à part. En plus la traduction pour "name" n'existe pas.

2024-02-28 13:37 UTC, AnthonyBourret commented on src/components/customElements/SongCard.tsx
> +import { ar } from 'vitest/dist/reporters-5f784f42';
Erreur avec l'auto-complétions je pense. C'est effacé

2024-02-28 13:39 UTC, AnthonyBourret commented on src/components/customElements/SongCard.tsx
> +              Année
La valeur est inscrite en dur en attendant la maj de l'API. On ne peut pas récupérer l'année pour une chanson. Inutile de traduire donc

2024-02-28 13:43 UTC, AnthonyBourret commented on src/components/customElements/AlbumCard.tsx
> +          <p className="font-bold">{capitalize(title)}</p>
Je sais mais c'était pour tester le développement en TDD

2024-03-02 12:52 UTC, Joliwood commented
- [ ] Il faudrait pouvoir dans les albums ou songs, avoir le choix de "tout afficher", ici on est obligé de sélectionner une durée (pour l'ex album) sans pouvoir revenir en arrière en tout affichant
- [ ] Bug affichage songs & album > reset order > affichage des albums, rien ne s'affiche
- [ ] Bug affichage songs > bouton refresh order ne fonctionne pas (sûrement lié au bug précédent)
- [ ] Il y a un console.log qui montre toute les traductions par i18n, il faudrait l'enlever

2024-03-02 12:56 UTC, Joliwood requested changes
- [ ] Il faudrait pouvoir dans les albums ou songs, avoir le choix de "tout afficher", ici on est obligé de sélectionner une durée (pour l'ex album) sans pouvoir revenir en arrière en tout affichant
- [ ] Bug affichage songs & album > reset order > affichage des albums, rien ne s'affiche
- [x] Bug affichage songs > bouton refresh order ne fonctionne pas (sûrement lié au bug précédent)
- [ ] Il y a un console.log qui montre toute les traductions par i18n, il faudrait l'enlever

2024-03-04 23:36 UTC, Joliwood requested changes

2024-03-04 23:36 UTC, Joliwood commented on src/components/customElements/FavCheckBox.tsx
> +          <AddIconUnchecked width="32px" height="32px" />
Il manque une prop, ou alors changer le type des props svg, cela génère une erreur

2024-03-04 23:36 UTC, Joliwood commented on src/components/customElements/SongCard.tsx
> +/* eslint-disable jsx-a11y/label-has-associated-control */
rule eslint inutilisée

2024-03-15 11:50 UTC, Joliwood requested changes

2024-03-15 11:50 UTC, Joliwood commented on src/svg/addIconChecked.tsx
Vu que tu ajoutes en svgprops un color en optionel, le mieux est de l'intégrer directement, pour l'exemple de AddIconChecked : 

```
import React from 'react';
import { SVGProps } from '../types';

function AddIconChecked(props: SVGProps): JSX.Element {
  const { width, height, color = '#dedede' } = props;
  return (
    <svg width={width} height={height} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke={color} strokeWidth="0.72">
      <g id="SVGRepo_bgCarrier" strokeWidth="0" />
      <g id="SVGRepo_tracerCarrier" strokeLinecap="round" strokeLinejoin="round" />
      <g id="SVGRepo_iconCarrier">
        <g id="style=bulk">
          <g id="heart">
            <path id="vector (Stroke)" fillRule="evenodd" clipRule="evenodd" d="M1.25 8.6901C1.25 5.18939 4.07229 2.3501 7.56 2.3501C9.29674 2.3501 10.8646 3.05608 12.0003 4.19481C13.1385 3.05574 14.7122 2.3501 16.44 2.3501C19.9277 2.3501 22.75 5.18939 22.75 8.6901C22.75 12.4396 21.0107 15.4002 18.9342 17.5277C16.8683 19.6444 14.4235 20.9862 12.8657 21.5187C12.5914 21.6148 12.2773 21.6501 12 21.6501C11.7227 21.6501 11.4086 21.6148 11.1343 21.5187C9.57655 20.9862 7.13169 19.6444 5.06577 17.5277C2.98932 15.4002 1.25 12.4396 1.25 8.6901Z" fill="#af373b" />
            <path id="vector (Stroke)_2" fillRule="evenodd" clipRule="evenodd" d="M19.7245 10.2553C20.1197 10.3793 20.3396 10.8002 20.2156 11.1954C19.3678 13.8974 17.6284 16.0256 15.8181 17.5708C15.5031 17.8397 15.0297 17.8023 14.7607 17.4872C14.4918 17.1722 14.5292 16.6988 14.8443 16.4299C16.5095 15.0085 18.0447 13.1038 18.7844 10.7464C18.9084 10.3512 19.3293 10.1313 19.7245 10.2553Z" fill="#af373b" />
          </g>
        </g>
      </g>
    </svg>
  );
}

export default AddIconChecked;
```

De cette façon, tu utilises la prop color seulement si elle est utilisée, et est initialisée par défault à '#dedede', ce qui était le cas avant

2024-03-17 11:41 UTC, Joliwood approved these changes

2024-03-17 11:41 UTC, merged