🎉 Favorites
AnthonyBourret/Soundy pull request #22
Opened 2024-04-07 13:24 UTC by AnthonyBourret

2024-04-07 21:16 UTC, Joliwood requested changes

2024-04-07 21:16 UTC, Joliwood commented on src/svg/index.ts
> +export { default as ArrowDown } from './arrowDown';
Chez moi c'est bugué, quand tu changes que le caseSensitive, ça ne push pas sur github, il faut par exemple renommer le fichier logoo.tsx puis Logo.tsx, mais de toute manière en terme de convention, il faut garder les noms des fichiers jsx en PascalCase.tsx

2024-04-08 14:23 UTC, AnthonyBourret commented on src/components/listenPage/AlbumDisplay.tsx
> +      return;
? J'ai pas compris

2024-04-08 18:19 UTC, Joliwood commented on src/components/listenPage/AlbumDisplay.tsx
> +      return;
@AnthonyBourret techniquement mettre un return; sans rien n'a pas d'intérêt car tu as fait une action dans l'appel de la fonction, donc autant là pour cette ligne faire un return setSortedAlbums([]);

2024-04-15 18:38 UTC, Joliwood approved these changes

2024-04-15 18:38 UTC, merged