:tada: Title suppression
AnthonyBourret/Soundy pull request #37
Opened 2024-05-25 22:05 UTC by Joliwood

2024-05-26 13:18 UTC, AnthonyBourret requested changes

2024-05-26 13:18 UTC, AnthonyBourret commented on src/components/listenPage/SongDisplay.tsx
>    likable = false,
Il faut mettre le likable a "true" pour afficher l'icône d'ajout aux favoris, là je n'ai rien

2024-05-26 13:18 UTC, AnthonyBourret commented on src/svg/PencilIcon.tsx
> +    fill="currentColor"
J'ai essayé de mettre la même couleur que primary (#af373b) et je trouve que ça donne pas mal ! 
![2024-05-26_15h15_03](https://github.com/AnthonyBourret/Soundy/assets/127198152/e43ff4bc-2fac-4484-bf1a-a364c2ecca79)
A toi de voir c'est du chipotage !

2024-05-26 13:18 UTC, AnthonyBourret commented on src/svg/PencilIcon.tsx
> +      stroke="#000"
Pareil là aussi même couleur que primary

2024-05-28 05:08 UTC, Joliwood commented on src/components/listenPage/SongDisplay.tsx
>    likable = false,
Regarde dans ProfileSongOrAlbum.tsx ligne 37, c'est bien précisé à true, le mettre comme ça dans songdisplay ligne 17 permet juste de définir le par défaut de la prop si elle n'est pas précisée (je ne voulais pas toucher ce que tu avais fait dans le fichier Listen.tsx, histoire de rien casser)

2024-05-28 05:10 UTC, Joliwood commented on src/svg/PencilIcon.tsx
> +    fill="currentColor"
Ouai j'avais essayé mais perso je trouvais ça moins clair surtout au fait que le svg est un peu petit

2024-05-28 16:00 UTC, AnthonyBourret commented on src/components/listenPage/SongDisplay.tsx
>    likable = false,
Le likable est sur la ligne 19, my bad j'ai sélectionné la mauvaise ligne, le fromProfilePage marche en effet. Mais pas le likable, sur le composant songDisplay il doit être à "true". Sinon le bouton d'ajout aux favoris n'apparait pas.

2024-05-29 10:16 UTC, AnthonyBourret approved these changes

2024-05-29 10:16 UTC, merged