🎉 Search listen page
AnthonyBourret/Soundy pull request #38
Opened 2024-05-28 16:14 UTC by AnthonyBourret

2024-05-28 21:20 UTC, Joliwood requested changes

2024-05-28 21:20 UTC, Joliwood commented on src/components/customElements/FilterRadio.tsx
> +  value?: ReleaseYear | DurationRange | undefined;
Pas besoin de repréciser le undefined, il y est déjà avec le ? juste après l'index

2024-05-28 21:20 UTC, Joliwood commented on src/components/listenPage/SearchBar.tsx
> +  setDurationFilter: React.Dispatch<React.SetStateAction<DurationRange | undefined>>;
undefined à mettre avec des ?

2024-05-28 21:20 UTC, Joliwood commented on src/components/listenPage/SearchBar.tsx
> +import {
mieux de préciser les imports si on peut

2024-05-28 21:20 UTC, Joliwood commented on src/components/listenPage/SearchBar.tsx
>    chosenDisplay: string;
Là tu peux en profiter pour éviter tout bug, de mettre : "songs" | "albums" comme ça pas de risque de plantage front

2024-05-29 10:11 UTC, AnthonyBourret commented on src/components/listenPage/SearchBar.tsx
> +  setDurationFilter: React.Dispatch<React.SetStateAction<DurationRange | undefined>>;
J'ai une erreur typescript quand je place le undefined avec un ?. Alors qu'avec la valeur en toute lettre pas de soucis . Pour que ça passe je dois définir une valeur { } sur chaque input, c'est pas super

2024-05-29 10:15 UTC, AnthonyBourret commented on src/components/listenPage/SearchBar.tsx
> +import {
Là je ne peux pas préciser le import type car je me sers des valeurs enums pour la définir la value des inputs. Je ne sais pas si c'est une bonne pratique mais dans un sens ça assure que la valeur de l'input soit la bonne.

2024-05-29 20:14 UTC, Joliwood approved these changes

2024-05-29 20:14 UTC, merged